import { iletisimEpostasi } from '@/config/seller'

export default {
  giris: 'These terms govern the mutual rights and obligations that apply when you use LocalKarar. By creating an account, you agree to these terms.',
  bolumler: [
    { id: 'taraflar', baslik: '1. Parties', paragraflar: ['These terms are between you and Enes Buğra Aslanhan (an individual located in Yenimahalle, Ankara), who operates the application.', `Contact: ${iletisimEpostasi()}`] },
    { id: 'hizmet', baslik: '2. Scope of the service', paragraflar: ['LocalKarar provides courses, Calculations, step-by-step Decision Tools, business profiles and records, AI Mentor, news compiled from official sources, and community features for small businesses. Financial models are detailed flows within Calculations, not a separate service.', 'The service is provided as available. Features may change for product, security, or legal reasons.'] },
    { id: 'hesap', baslik: '3. Account and security', liste: ['Provide accurate and current account information.', 'Keep your password and devices secure and do not share your account.', 'Tell us promptly if you suspect unauthorised access.', 'You are responsible for activity carried out through your account unless the law provides otherwise.'] },
    { id: 'danismanlik-degildir', baslik: '4. The service is not professional advice', paragraflar: ['Content, calculations, Decision Tools, news summaries, and AI Mentor responses are general information and decision-support materials. They are not legal, tax, accounting, investment, medical, or other professional advice.', 'Outputs depend on the information and assumptions supplied. Verify important figures, rules, deadlines, and decisions with official sources and a qualified professional where appropriate.'] },
    { id: 'yapay-zeka', baslik: '5. Nature of artificial-intelligence output', paragraflar: ['AI Mentor generates responses using a language model. A response may be incomplete, outdated, or incorrect even when it sounds confident.', 'Where possible, the service grounds responses in the LocalKarar content library and displays sources, but accuracy is not guaranteed.', 'Before acting, verify information involving amounts, rates, dates, deadlines, or legislation against an official source. AI responses remain subject to section 4.'] },
    { id: 'kullanici-icerigi', baslik: '6. Content you upload', paragraflar: ['You retain your rights in documents, records, and posts you upload.', 'You authorise us to store, process, and display that content back to you only as needed to provide the service. Your content is not used for marketing or to train artificial-intelligence models.'] },
    { id: 'ucuncu-kisi-verileri', baslik: '7. Third-party data — your responsibility', paragraflar: ['When you create account records or upload invoices and similar documents, you may enter personal data relating to customers, suppliers, or employees.', 'For that data, you are the data controller under the KVKK and LocalKarar acts only as your data processor and on your instructions.'], liste: ['You must have a valid legal basis for processing the data.', 'You must provide the notices required by the KVKK.', 'You must handle requests to access, correct, or erase the data; the application provides tools to assist you.', 'Do not enter special-category personal data such as health, criminal-conviction, or biometric data. The application is not designed to process it.'] },
    { id: 'yasak-kullanim', baslik: '8. Prohibited use', paragraflar: ['The following conduct violates these terms:'], liste: ['Sharing unlawful or misleading content or content that infringes another person’s rights', 'Attempting unauthorised access to another account', 'Bypassing security or rate limits, or overloading the service', 'Automated bulk extraction of application data', 'Using AI Mentor outside its intended purpose or to generate harmful content', 'Using the application to process personal data unlawfully'] },
    { id: 'topluluk', baslik: '9. Community rules and moderation', paragraflar: ['Community posts are published immediately without prior review. You remain responsible for ensuring that your content is lawful, original, and respectful.', 'You can remove your own post. LocalKarar may remove rule-breaking content and restrict community access for repeated violations. Complaint and audit records may be retained after content is removed.', 'Replies and quotes are posts governed by the same rules. Likes are shown as totals; saved posts are private to you.', 'Do not post business information you do not want other members to see.', 'Private one-to-one and group messages are not shown to other community members, but they are NOT END-TO-END ENCRYPTED. They are stored on the server and may be accessed by administrators only when a complaint must be investigated.', 'Blocking prevents the parties from messaging or viewing each other’s profiles and posts. Complaint records are retained as an audit trail so repeated reports can be assessed.'] },
    { id: 'gelen-kutusu', baslik: '10. Your business inbox', paragraflar: ['You may enable a dedicated email address in business settings. Invoices and documents sent to it are processed like manual uploads and become proposals awaiting your approval; no record is final until you approve it.', 'The inbox is off by default and can be disabled or regenerated at any time.', 'Only verified workspace members and addresses you explicitly add as trusted senders may send documents. Other messages are discarded without notifying the sender. Messages that fail DKIM or SPF verification are not processed.', 'Do not share the address unnecessarily. Regenerate it if it is exposed. Documents may contain third-party personal data, so your obligations under section 7 apply.'] },
    { id: 'pazaryeri-baglantisi', baslik: '11. Marketplace store connection', paragraflar: ['You may connect a Trendyol, Hepsiburada, n11, or Shopify store in business settings. No connection exists by default, and you may remove it at any time.', 'API keys and access credentials are stored encrypted and are never shown again in a screen or API response.', 'You confirm that you are authorised to connect the store and that doing so complies with the marketplace’s terms. LocalKarar is not a party to your agreement with the marketplace.', 'Imported orders may include buyer names; your obligations under section 7 apply. Record proposals created from marketplace data require your approval.', 'The marketplace is responsible for the accuracy of its data. Use the marketplace’s own records as the official source for accounting and declarations.'] },
    { id: 'abonelik', baslik: '12. Membership, billing, and cancellation', paragraflar: ['LocalKarar membership is a paid service. The free usage period granted before billing starts, the prices, the billing periods, and the nature of the founding-member discount are set out in detail in the Subscription and Billing Terms.', 'Purchases are made under the Distance Service Agreement and the Pre-Contract Information Form. At the payment step you are asked to accept those documents and, separately, to confirm that performance may begin immediately.', 'You may end your membership at any time from Settings → Membership and Billing, without giving a reason. On cancellation your access continues until the end of the period you have paid for; no partial refund is made for unused days.', 'When the free usage period ends, or when a charge cannot be collected, your account moves to read-only mode. Your data remains visible and exportable; nothing is deleted.', 'Price changes are announced before they take effect, and the price of the current period is not changed during that period.'] },
    { id: 'fikri-mulkiyet', baslik: '13. Intellectual property', paragraflar: ['Rights in the interface, software, learning content, Decision Tools, and calculation templates are reserved.', 'You may use the content for your own business. Reproduction, republication, or commercial distribution requires written permission.', 'News summaries identify their official source; rights in the original material belong to the relevant institution.'] },
    { id: 'hizmet-degisiklikleri', baslik: '14. Changes, suspension, and termination', paragraflar: ['Features may be added, changed, or removed. Material changes will be announced through appropriate channels.', 'An account may be suspended or terminated for a breach. Unless legally prevented, we will explain the reason and allow a reasonable period to export your data.'] },
    { id: 'sorumluluk', baslik: '15. Limitation of liability', paragraflar: ['The service is supplied without a promise that it will be uninterrupted or error-free. Maintenance, provider failures, or security requirements may cause temporary disruption.', 'LocalKarar does not accept responsibility for business decisions made on the basis of application information or AI responses.', 'These limits do not affect liability that cannot legally be limited or your rights under consumer law.'] },
    { id: 'hesap-sonu', baslik: '16. Closing your account', paragraflar: ['You may delete your account from Settings at any time.', 'If you are the sole owner of a workspace, you must first transfer ownership to another member.', 'The retention section of the Privacy and KVKK Notice explains what happens to data after deletion.'] },
    { id: 'uygulanacak-hukuk', baslik: '17. Governing law and jurisdiction', paragraflar: ['Turkish law governs these terms.', 'The courts and enforcement offices of Ankara have jurisdiction. If you qualify as a consumer, your rights to apply to consumer arbitration committees and consumer courts remain reserved.'] },
    { id: 'yururluk', baslik: '18. Effective date and changes', paragraflar: ['These terms take effect when you create an account.', 'Updates are published under a new version. Settings displays the current text and asks you to consent again. The version at the top of the page identifies the terms currently in effect.'] }
  ]
}
